### ISSUE TITLE
Distance correction?

### ISSUE THREAD

**Issue by rudybroersma** [agittins/bermuda#227] opened 2024-06-29 19:04 UTC
**Is your feature request related to a problem? Please describe.**
I have 2 Bluetooth Proxies in my living/dining room (which is one open area). There is about 10 meter distance between both sensors. If someone is sitting at the end of the living room (around the blue line), he's in the middle of both sensors, causing the reading to bounce between 2 locations.

**Describe the solution you'd like**
I would like to be able to add a penalty to specific proxies. Lower the receiver strength (if that's possible) or something like that.
Anything to correct/alter positioning.

eg. I would like to add 3 meters to the distances to all discovered devices from proxy 0a1b2c

This way, if someone is sitting in between the living room and the dining room, it'll measure it as:
'Living room: 5 meters'
'Dining room: 8 meters'

Instead of both 5  meters.

Because a picture says a thousand words:
- 2 Bluetooth Proxies in both corners (blue circles)
- Blue line is center of the room and is when I get equal distance readings from both proxies
- Red line is what I consider the border between livingroom and dining room

So what I want is to be able to make some sort of correction to alter measurements so that the red line becomes the tipping point for determining the area a beacon is in, instead of the blue line.

![image](https://github.com/agittins/bermuda/assets/2853200/2d9ae173-6e51-4afa-932d-957f71555e25)

**Comment by agittins** [comment] 2024-06-29 19:36
Howdy! I have a similar situation (and issue) in my kitchen/dining areas.

This is effectively a duplicate of #45 

The change proposed in #45 will provide settings so that you can tune the `ref_power` per proxy, effectively letting you alter the interpreted distance on a proxy by proxy basis.

Also worth noting that when I get the trilateration support done, this should greatly improve the situation, since then we'll be calculating (effectively) a point in XY space rather than a binary yes/no by area - but that's still a bit of an unknown as to how well that will work, so in the meantime having per-proxy adjustments should help out with your issue.

To keep the issue queue a bit easier to manage, I'll mark this as a duplicate and close it, so we can track the progress just on #45.

Feel free to follow that issue for updates!

**Comment by agittins** [comment] 2024-06-29 19:36
duplicate of #45

**Closed by agittins** 2024-06-29 19:36 UTC
Labels: duplicate

**Comment by rudybroersma** [comment] 2024-06-29 19:38
Ah, sorry I missed that one! Looking forward to seeing #45 implemented :)
