### ISSUE TITLE
Ignore/disable scanner

### ISSUE THREAD

**Issue by adidoes** [agittins/bermuda#277] opened 2024-08-04 23:52 UTC
Hello, I'm not really sure what I'm asking for here since I don't fully understand how Bermuda works under the hood.

I have an issue with my local bluetooth adapter (apple onboard bluetooth, my HA runs on a mac mini with ubuntu), the tracker keeps jumping between the actual room I'm in (bedroom) to the living room (where the mac mini is) even though the distance to the Shelly proxy is smaller than the distance to mac mini.

I believe this has something to do with the power and range of the local bluetooth adapter and I was wondering if I can configure Bermuda to ignore it as a scanner?

I'm open to other solutions as well, thanks!

**Comment by agittins** [comment] 2024-08-05 15:49
Hi @adidoes, yes this is a common issue due to many bluetooth dongles seeming to have more sensitive receivers than the esphome and Shelly units.

The fix, which should be available AnyDayNow :tm: is being worked on and is being tracked at #45 - it will allow you to specify an "offset" for each proxy. This will let you calibrate the proxies relative to each other.

I'll mark this as a duplicate of #45 and suggest that if you jump over to that issue and click the "Subscribe" button for the issue it will keep you up to date on progress.

**Comment by agittins** [comment] 2024-08-05 15:49
Duplicate of #45

**Closed by agittins** 2024-08-05 15:49 UTC

**Comment by adidoes** [comment] 2024-08-05 18:01
Thanks @agittins, I'm gonna follow #45
