### ISSUE TITLE
Last Seen (Last Area) Sensor

### ISSUE THREAD

**Issue by 6of6** [agittins/bermuda#311] opened 2024-09-28 06:06 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 6of6** [comment] 2024-09-28 06:20
I recently created my own sensor to save the last "valid" result from "sensor.phoneBLE_area". It was harder than I thought it would be.

My "problem" is that my phone will sleep from time to time (seems common). That said, it seems impossible to actually pick it up and move it somewhere WITHOUT "it" knowing. (It always wakes up).

I have a sensor that will show the last "valid" (not unknown/unavailable) location. I find it useful. I think it would be useful if it was built in. 

Thank you for making such a useful integration/application!

**Comment by agittins** [comment] 2024-09-29 05:13
Hi 6of6, thanks for your suggestion and well done setting up your own template for this.

It is something that has been requested previously and I have decided that I will implement it when I get the time to address it. The feature request is being tracked in issue #202 so I will close this one as a duplicate, and invite you to hop over to #202 and click the "Subscribe" button on that issue so you can stay up to date on progress, and contribute any of your findings or questions there.

Cheers!

**Comment by agittins** [comment] 2024-09-29 05:14
Duplicate of #202

**Closed by agittins** 2024-09-29 05:14 UTC
