### ISSUE TITLE
Max area radius setting ignored in 0.7

### ISSUE THREAD

**Issue by ronaldheft** [agittins/bermuda#366] opened 2024-11-08 16:40 UTC
## Configuration

Configured area detection radius: 5 meters
<img width="567" alt="SCR-20241108-kngt" src="https://github.com/user-attachments/assets/161a806c-0530-4f41-9e6d-9f91d1a4299e">
 
## Describe the bug

The setting is ignored. Currently seeing an area detected when meters are 100+.

<img width="581" alt="SCR-20241108-knew" src="https://github.com/user-attachments/assets/3b632aca-a337-4e98-bb13-aac3ceeae43e">

<img width="328" alt="SCR-20241108-knjf" src="https://github.com/user-attachments/assets/9531b357-b751-4f2b-81f7-1ddecf25888d">

## Diagnostics

[config_entry-bermuda-9e6b6e71fed70d3b1c5d89b3d1e3452e.json](https://github.com/user-attachments/files/17681532/config_entry-bermuda-9e6b6e71fed70d3b1c5d89b3d1e3452e.json)

**Comment by agittins** [comment] 2024-11-08 21:29
Hi Ron, thanks for your report!

I notice that one of your screenshots is of the calibration dialog in the config flow. Do you know if you have restarted or reloaded the integration since that calibration check?

The calibration screen doesn't honour the max_radius since it's a diagnostic tool, but I am wondering if maybe it has had a side-effect on the area matching, since it causes Bermuda to recalculate distances immediately when you `SUBMIT` that form.

The other possibility is that we have a regression after re-working some of the start-up code to improve performance and stability with recent HA async changes.

I'll see if I can replicate it here when I get a chance, but if you know if it's had a restart or reload (or could try one to check) that might give me some extra pointers in tracking down the issue.

**Comment by ronaldheft** [comment] 2024-11-08 21:44
Good thought about the calibration. I opened that dialog purely to better see what was happening with distances, so I wasn't adjusting the calibration when I noticed the bug.

To verify, I did just reload the integration and I'm seeing the same issue. I'm currently outside my house in my backyard, far from a BLE tracker, and it's still reporting my area by nearest BLE tracker that should be outside the radius.

![image](https://github.com/user-attachments/assets/0ffd886c-b3dc-4b78-ab7c-80b1cc1c92ce)

**Comment by agittins** [comment] 2024-11-08 21:50
Great, thanks for confirming that for me. I'll dig into it soon and let you know how I go.

**Comment by ronaldheft** [comment] 2024-11-12 17:09
Thanks @agittins! I am following #371 now, and I agree, this is related to metadevices. All the devices I have observed this on are IRK, private BLE devices.

I'm okay closing this in favor of tracking all activity on #371, if that's easier.

**Comment by agittins** [comment] 2024-11-13 03:37
Great, cheers!

I've just pushed a fix for #371 and it also appears to resolve this issue, at least with the testing I did on my system. I'll be packaging a release later today to include it.

**Closed by agittins** 2024-11-13 03:37 UTC
