### ISSUE TITLE
Bermuda repository is not searchable in HACS

### ISSUE THREAD

**Issue by wappinghigh** [agittins/bermuda#274] opened 2024-08-04 00:57 UTC
Hi

The repository is not searchable  in HACS right now.

Why is that?! 

Running latest version of HACS:

Integration version: | 1.34.0
-- | --
Frontend version: | 20220906112053
Repositories: | 1453

And HA:

Core
2024.7.4
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

**Comment by agittins** [comment] 2024-08-04 08:42
Thanks for taking the time to raise this.

Yeah, I don't know what the official status is for HACS' built-in repos. I submitted Bermuda to be included in the default repos a while ago (see #43 ) but each time I check it looks like they are not doing any adds to the repos, only removals. I think the burden of reviewing might have got a bit much for the team, perhaps.

The last merge of an added integration I can see in HACS was on Feb 26th this year, and there have been no integration repos merged in since. My understanding is (but only via hearsay, I can't see any official stance) is that there were perhaps github-related scaling issues, and all PR reviewing is on hold until that is solved, which might be via a V2 hacs which is being worked on - but again, I can only see people outside the project mentioning this, without links, so it might be only rumour. It's frustrating, but but I can imagine it being nowhere near as frustrating as trying to fix it! So I wouldn't recommend hassling the HACS team, but maybe search their various contact points to see if there's an official statement anywhere, and otherwise I suggest we let them take care of it in time.

For now, having the "add to hacs" button on individual project repos solves the installation difficulty, but it would be nice to have the discovery features of hacs back again.

I'll close this as a duplicate of #43, so if you find any *official* info feel free to bring it up there.

**Comment by agittins** [comment] 2024-08-04 08:43
Duplicate of #43

**Closed by agittins** 2024-08-04 08:43 UTC

**Comment by agittins** [comment] 2024-08-04 08:45
Ahh.. found a comment from Frenck in the HACS discord in April:

> Frenck — 04/11/2024 7:04 PM
> The problem is not the reviews at this point. 
> 
> As far as I am aware / understood, the problem is the technical limits HACS is running into on a capacity level. HACS v2 should resolve that, that has been in progress

There's no estimate on when HACS v2 will be out, so I think best we can do is just sit tight and let the folks do their thing.

**Comment by coxtor** [comment] 2024-09-09 10:52
Hi, on Hacs 2.0 the integration can not be found.

**Comment by agittins** [comment] 2024-10-29 17:24
> Hi, on Hacs 2.0 the integration can not be found.

Yes, they still haven't re-started merging new repos, so I don't know what the plan is, just that one of the blockers (hacs v2) had been met.
