### ISSUE TITLE
MQTT data format

### ISSUE THREAD

**Issue by WyriHaximus** [agittins/bermuda#221] opened 2024-06-23 16:40 UTC
For Bluetooth presence detection, I'm looking into using a few shelly plugs with Bluetooth and Bermuda to do device triangulation. My catch however is that I can't use Bluetooth from Home Assistant directly due to the way I'm running it. However, with the scripting on the Shelly plugs I can do the detection and send the information over MQTT to HA instead of Bluetooth.

The device detection and shipping it to MQTT works. What is currently missing however is in which format to send it to MQTT. Unless I'm blind, which wouldn't be the first time, there isn't information in the wiki on the data format expected. Can someone point me in the direction to that?

**Comment by agittins** [comment] 2024-06-24 07:09
The only supported way (ie, it's known to work) is to use the Shelly integration in HA: https://github.com/agittins/bermuda/wiki/Shelly-Device-configuration

Note that the proxied data is not "sent via bluetooth", it's sent via Wifi.

Would this work for you?

**Comment by agittins** [comment] 2024-06-28 10:24
I'm going to close this one.

For the record, to do what you are describing you'd need to write a whole new integration in HA, that took data from mqtt and pumped it into HA's internal bluetooth structures.

You'd have to do that yourself, as it's unlikely to be something anyone else would need, unless you can clarify what you mean by "I can't use Bluetooth from Home Assistant directly due to the way I'm running it."

Happy to provide some further guidance if you want to explain your setup and why the normal approach won't work for you.

**Closed by agittins** 2024-06-28 10:24 UTC

**Comment by WyriHaximus** [comment] 2024-07-01 18:44
>You'd have to do that yourself, as it's unlikely to be something anyone else would need, unless you can clarify what you mean by "I can't use Bluetooth from Home Assistant directly due to the way I'm running it."
> Happy to provide some further guidance if you want to explain your setup and why the normal approach won't work for you.

Running HA inside Kubernetes using talos.dev, which doesn't ship with any wireless drivers. Which means I can't enable Bluetooth in HA and unlock the data that cames from the shellys.

**Comment by agittins** [comment] 2024-07-01 21:51
Hmm. You don't need any bluetooth hardware on HA's system in order to use the bluetooth features. When using an esphome bluetooth proxy, everything *just works*:tm: even without anything to specifically enable the bluetooth integration, and with no local bluetooth hardware/drivers.

Have you confirmed that the shelly integration's built-in bt proxy script doesn't act the same way?

**Comment by WyriHaximus** [comment] 2024-07-02 08:46
Ok cool so this shouldn't matter at all then: 
![image](https://github.com/agittins/bermuda/assets/147145/34bafff6-b53a-4341-ac6b-7f034c44f090)

There is no esphome Bluetooth proxy in play tho. It looks like shellys build in proxy doesn't work that way as nothing is showing up. But let me dive into that

**Comment by agittins** [comment] 2024-07-03 10:53
> It looks like shellys build in proxy doesn't work that way as nothing is showing up

There's nothing unusual about your config given what you've shown - I expect it should just work. My suggestion is to have a go at making it work, and if it doesn't work, share what you tried and what you saw, rather than only stating your conclusion about what it means. I've fallen into this myself a number of times, it's a normal pattern when one is used to having to work stuff out alone! :-)

A good first diagnostic step is to call Bermuda's `dump_devices` service, which will show you what it has found in HA's bluetooth backend. HA does lack good user-discoverability for bluetooth when there's no physical adaptor since it doesn't surface a visible entity for it, but the backend is still doing its thing regardless.

Happy to help out to get it up and running for you, but I'll need some solid observations to work from 👍🏼 

Feel free to create a new issue or reopen this one if you run into any trouble.

**Comment by WyriHaximus** [comment] 2024-07-08 21:26
Thanks for the help, it turns out I'm an idiot and it works fine once you understand how it all works, and that the HA and Bermuda UI doesn't show you anything until it works it's slightly confusing. 

![image](https://github.com/agittins/bermuda/assets/147145/96a5f2f8-4635-4514-9441-c1a2f56dbcc5)

The thing that didn't help is that Bermuda doesn't show `select devices` unless it has data on them. Potentially showing a `no devices found` on this screen could be indicative:
![image](https://github.com/agittins/bermuda/assets/147145/19c3415e-1f9f-4d91-9903-395715f22a83)

One piece of feedback as well is that depending on the transmit power I've set in the HA app a difference the distance to a shelly plug changes. It would be great if Bermuda would take that bit of information into account. However, I'm not sure if that information is available for Bermuda.

**Comment by WyriHaximus** [comment] 2024-07-09 21:26
> Oh, that's interesting. I had no idea that menu didn't appear if there were no devices. That's definitely worth sorting out, not a great user-experience! (as you well know)

Also I'm running on a not so common deployment method. Most situations should have Bluetooth available and addable though the UI. That is what initially fully threw me off.

> Re distance calculations etc, this is just part of the whole "calculating distance by signal strength" deal. There's an issue for adding per-device rssi calibration for reference-power, but with the current set-up everything is relative (ie, it doesn't matter if it says 1m or 100m, it's the relative difference between the distance to one proxy vs the distance to another proxy that matters). However when I get trilateration implemented it's going to be more important to have that flexibility, so it will be coming along with that. In the meantime, altering the `ref_power` and `attenuation` settings are the only control you have over how the distances are calculated, but these apply to all devices, currently.

Made sure today that all devices are in the correct room and each room is on the correct floor. Current only `Kubernetes Midespace Station Switch` is in the `Attic`. The rest are two stairs down in the livingroom. That screenshot is from what I was in range for all of them. With the app broadcasting and high strength. Will probably lower that because as you said the numbers don't really matter as long as it's consistent. And the placement of the Shellys will matter to some degree. 

> I'll give some thought to how Bermuda could give a bit more guidance when setting up, especially about whether it can give you some feedback about whether any scanners appear to be present, and if they're sending data - I think that would help a lot for people first setting up, because as you noted, the entire stack gives very little feedback about what's going on.

Exactly that, maybe send a notification when Bermuda finds a device for the very first time. Having additional information for each discovered device could help. For example, I just found an ibeacon in my set up and I have no clue which device it is. Not sure if BT MAC addresses have a vendor prefix like WiFI MAC addresses do.

**Comment by agittins** [comment] 2024-07-16 01:17
> Also I'm running on a not so common deployment method. Most situations should have Bluetooth available and addable though the UI. That is what initially fully threw me off.

Yeah, awkwardly, only systems with a local bluetooth adaptor will show the Bluetooth integration in the GUI, even though it's always there in the background. This makes it hard to intuitively discover what's going on.

I've added some info to the config dialogs now that should help a bit with this. It will tell you how many scanners and devices it can see, and how many of those are "active" (seen within the last 10 seconds). I've also added some text to the devices dialog so it's less confusing if there are no devices to configure:

![image](https://github.com/user-attachments/assets/91658df7-b439-4dea-a6d3-1c8a91439e7e)
![image](https://github.com/user-attachments/assets/bec700de-3fb2-48f9-89a7-d93970504645)

This should help with people who install Bermuda but then can't tell if anything is working or not - which I think happens moderately often.

I think BT MACs do have vendor prefixes, but a lot of devices these days will use addresses in the random ranges now, so it's less useful than it was for Ethernet - but I could be slightly off on that.

Notifying on new devices is tricky because many people will be living close enough to neighbours or passing traffic that they'll always have new devices popping up. I'll give some thought though to have the config process be a bit more helpful, say by highlighting devices with particularly strong signals so you can easily identify a device by putting it next to a proxy.

Anyway, just wanted to let you know that those changes will be in the next version, and thanks for the nudge on that, and also for your direct support, too - much appreciated!

**Comment by WyriHaximus** [comment] 2024-07-17 20:55
> > Also I'm running on a not so common deployment method. Most situations should have Bluetooth available and addable though the UI. That is what initially fully threw me off.
> 
> Yeah, awkwardly, only systems with a local bluetooth adaptor will show the Bluetooth integration in the GUI, even though it's always there in the background. This makes it hard to intuitively discover what's going on.

Yeah that really messed it up for me. Still not sure why they went with that.

> I've added some info to the config dialogs now that should help a bit with this. It will tell you how many scanners and devices it can see, and how many of those are "active" (seen within the last 10 seconds). I've also added some text to the devices dialog so it's less confusing if there are no devices to configure:
> 
> This should help with people who install Bermuda but then can't tell if anything is working or not - which I think happens moderately often.

Hah sweet!

![image](https://github.com/user-attachments/assets/71b8754b-34e7-462e-8609-0207a8c928b8)

> I think BT MACs do have vendor prefixes, but a lot of devices these days will use addresses in the random ranges now, so it's less useful than it was for Ethernet - but I could be slightly off on that.

Thought about that, our phones will randomize the MAC per WiFi SSID, Bluetooth probably does the same.

> Notifying on new devices is tricky because many people will be living close enough to neighbours or passing traffic that they'll always have new devices popping up. I'll give some thought though to have the config process be a bit more helpful, say by highlighting devices with particularly strong signals so you can easily identify a device by putting it next to a proxy.

Was thinking more about for the initial set-up to notify the user that Bermuda got something. Definitely not want to have it for everything. We live near a major route within our neighbourhood. So most traffic in or out passed in front of our house. For sure not want to be notified at 3 in the morning when people are coming back from going out 🤣 .

> Anyway, just wanted to let you know that those changes will be in the next version, and thanks for the nudge on that, and also for your direct support, too - much appreciated!

Much appreciate your work as this will be the most useful tool for us besides HA and Node Red. Will swap it to a lower but monthly because it didn't let me do both 😅 .
