### ISSUE TITLE
Track last known location 

### ISSUE THREAD

**Issue by jonlove234** [agittins/bermuda#252] opened 2024-07-19 17:58 UTC
**Is your feature request related to a problem? Please describe.**
I've noticed that some devices - like remote controls with Bluetooth - only scan/activate intermittently. Rather than have them show up as unknown location, would be useful if the last triangulated location were tracked. 

**Describe the solution you'd like**
Additional attribute that maintains the last known triangulated location, potentially timestamped and with the distance too.

**Describe alternatives you've considered**
It's possible there's a way to code this using a template but it's perhaps not the optimal approach.

**Additional context**
![Screenshot_20240719-135807](https://github.com/user-attachments/assets/6f687a6a-89ad-41b1-8a68-059b8963e150)

**Comment by jonlove234** [comment] 2024-07-19 18:01
Apologies this may be a dupe of https://github.com/agittins/bermuda/issues/202

In my case it was for remotes that ping intermittently and not necessarily battery depleting but same functionality.

**Comment by agittins** [comment] 2024-07-20 16:17
Interesting, I am guessing that the remote only sends adverts when its in use. Thanks for the helpful report of the issue.

Functionally, yes this would be the same functionality of #202, but gives extra weight to that feature request given you have a product that intrinsically behaves that way.

I'll mark this as duplicate of #202, I'd suggest subscribing to that issue if you haven't already.

**Comment by agittins** [comment] 2024-07-20 16:17
duplicate of #202

**Closed by agittins** 2024-07-20 16:17 UTC
