### ISSUE TITLE
"not_home" to "unavailable" after reboot HA

### ISSUE THREAD

**Issue by vakkerman** [agittins/bermuda#302] opened 2024-09-13 06:34 UTC
version 0.6.8

my tracker status turns to "unavailable" from "not_home" if I reboot home assistant. Tracking of 2 devices act the same

![unav](https://github.com/user-attachments/assets/34151cc6-e9f4-4a2b-a3d2-6ec198364db7)

**Comment by agittins** [comment] 2024-09-15 07:02
Duplicate of #235 

Hi @vakkerman you should find this is resolved in v0.6.9rc2, which you can install via hacs by enabling the "show beta versions".

**Closed by agittins** 2024-09-15 07:02 UTC
