### ISSUE TITLE
Version is not displayed in Integration Page

### ISSUE THREAD

**Issue by fwmarcel** [agittins/bermuda#241] opened 2024-07-14 10:47 UTC
## Version of the custom_component

v0.6.7

## Describe the bug

The version is not displayed on the integration page.
The version should be in the manifest.json in order to be displayed correctly.

```
{
  "domain": "bermuda",
  "name": "Bermuda BLE Trilateration",
  "bluetooth": [
    {
      "connectable": false,
      "manufacturer_id": 76
    }
  ],
  "codeowners": ["@agittins"],
  "config_flow": true,
  "dependencies": ["bluetooth_adapters", "device_tracker"],
  "documentation": "https://github.com/agittins/bermuda",
  "integration_type": "device",
  "iot_class": "calculated",
  "issue_tracker": "https://github.com/agittins/bermuda/issues",
  "requirements": [],
  "version": "0.0.0"
}
```

<img width="704" alt="Screenshot 2024-07-14 at 12 40 57" src="https://github.com/user-attachments/assets/e3135bc2-9e3b-42dc-9518-c2ab65974384">

**Comment by agittins** [comment] 2024-07-14 11:00
Howdy, and thanks for bringing this up.

It's something I did the rounds on long ago and couldn't find a solution I was OK with. In particular, it seemed to me at the time that HACS was pulling from the repo rather than the zipped release file, so was showing 0.0.0 even though the released files had versions in them. I have a personal conviction that the files in the repository heads should not have version numbers in them, and I couldn't find a way around it at the time (I remember I looked at the Grocy integration and wasn't happy with adopting however it was they were doing it).

However, I've just taken a look at the Spook integration (since I figured if there's a way, Franck would know) and it looks like it handles everything just fine, so I'll take a dig through his integration's config and see what it is I'm doing wrong.

**Comment by agittins** [comment] 2024-07-16 07:07
A win! I have just released v0.6.8 and it now shows the version number correctly! :D Thanks for the nudge!

**Comment by agittins** [comment] 2024-08-11 07:16
Sigh. So the problem with switching to zipped releases is that then the `main` download doesn't work, with a 404 (because there's no zip file maintained for the `main` branch).

I think I'm switching to a different model, of creating `draft` releases (rc / release-candidates) instead.
I'm still not entirely happy with it but it might be the only/best way that fits all my personal requirements. These are:

- Any branch that isn't tagged with a release version, should result in a version of 0.0.0 if it's checked out and run in HA.
- If an install identifies itself as a certain version, it should match bit-for-bit with a specifically-tagged commit in the repo, and no other commit in the repo should carry that version number.
- No manual input should be required to "manage" version numbers, the defaults chosen by workflows etc should be sensible enough to leave them be.
- It should be easy for people to download a non-release version inside HACS. (be it `main` or a specific non-release version)

I'm reopening this until I'm happy with it.

**Comment by agittins** [comment] 2024-11-07 07:37
I think I'm comfortable enough with the workflow of using pre-release / rc / beta releases for testing, and using zipped releases in hacs to close this one out now. The versioning in HACS2 is all working as intended as far as I can see, so I think we're all good now.

Thanks again for the nudge to revisit this, all those months ago! 😅

**Closed by agittins** 2024-11-07 07:37 UTC
Labels: build
