### ISSUE TITLE
Bermuda Has To Be Manually Reloaded if Home Assistant Is Restarted While Tracked Device Not Present

### ISSUE THREAD

**Issue by brooksben11** [agittins/bermuda#308] opened 2024-09-26 18:10 UTC
## Version of the custom_component

0.6.8

## Configuration

N/A

## Describe the bug

Whenever Home Assistant is restarted and the Bermuda tracked device isn't present (i.e. it's somewhere that HA can't 'see' it), the Bermuda associated entities stay unavailable indefinitely until Bermuda is manually reloaded.

## Debug log

N/A

**Comment by agittins** [comment] 2024-09-29 05:19
Hi Ben! Thanks for your report. This issue has been fixed in the current beta release, v0.6.9rc2. You can install it via HACs by enabling "Show beta versions" then re-downloading Bermuda - or you could wait until I formally release the next version, which should be fairly soon.

I'll mark this issue as a duplicate of the one that originally brought up the issue, #235 but feel free to re-open this one if you have any issues updating to 0.6.9rc2.

Cheers.

**Comment by agittins** [comment] 2024-09-29 05:19
Duplicate of #235

**Closed by agittins** 2024-09-29 05:19 UTC
