### ISSUE TITLE
Create a "last area" entity

### ISSUE THREAD

**Issue by jmthompson** [agittins/bermuda#294] opened 2024-08-21 19:25 UTC
**Is your feature request related to a problem? Please describe.**
A way to improve device location even when the device is not pinging (the HA companion on Android seems to occasionally stop pinging)

**Describe the solution you'd like**
Add a "last seen area" entity that would show what area a device was last seen in. It would only change when the device is actively detected in another area.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by agittins** [comment] 2024-08-21 21:45
Hi Joshua, a few others have asked for the same functionality, so I'll be including it in the next release. I'll close this as a dupe of #202, so I'd suggest subscribing to that issue so you'll get a notification when the feature gets committed, and can follow up with any questions etc.

I plan to implement this as a "hidden" or "disabled by default" sensor, so you can enable it for any devices you wish to track that way.

Duplicate of #202

**Comment by agittins** [comment] 2024-08-21 21:46
Duplicate of #202

**Closed by agittins** 2024-08-21 21:45 UTC
