### ISSUE TITLE
Suggestion to be able to select Bluetooth radios to use 

### ISSUE THREAD

**Issue by Zoriontsu** [agittins/bermuda#164] opened 2024-04-15 03:35 UTC
Just deployed yesterday and It is working great! 
Just one challenge:
I have four ESP32 proxys around my house, plus the Pi4 Bluetooth radio. The issue that I am facing is that the Pi4 captures most of the activity from the BLE devices nearby.

For example, while my smart watch is 1-2 meters from the Kitchen ESP32, the Pi4 (8-10 meters away) picks up a stronger signal  and provides a false location. 

It would be helpful to be to select which radios to utilize.

Thank you

**Comment by agittins** [comment] 2024-04-16 10:49
Hmmm good point.

I have an issue to implement independently calibrating both proxies and beacons at #45 that will let you effectively define the receiver sensitivity by proxy - so you'd offset the bluetooth adaptor so that it reported accurate distances.

This would solve the particular problem you are having, but I think the ability to disable a scanner completely from calculations is a good idea - we'll need it if/when we support scanners that are not fixed in location (like mounted on a robot vacuum etc).

Right now I'm tossing up where to put the configuration - whether to put it on the device page as an entity or whether to put it into the options_flow when you click the "Configure" button for Bermuda. The latter is starting to get a bit crowded, but it might be the better place for it.

I'll make a decision on that soon, and get a fix sorted. My bt dongle also gets a stronger signal than the esp32's, so yeah I get warped into the garage more often than I should, too! 😅

**Comment by User873902** [comment] 2024-04-27 23:54
This is exactly my issue. I have mainly two types of ESP32 boards that would require independent calibration of RSSI strength/sensitivity to achieve accurate placement. Looking forward to the independent calibration.

**Comment by User873902** [comment] 2024-05-09 21:21
While you're adding individual base station calibration, I would wonder if the area of each room could be specified as well. Some rooms are small and others are large. Shrinking area radius of the smaller rooms would be even more important when the adjoining room does not have an ESP32 base station.

**Comment by asucrews** [comment] 2024-05-11 20:48
Hello, I'd like to express my gratitude for the great project. It's working better for me than other projects of this type that I've tried. I suggest placing it on the device page as an entity, as putting it on the configuration page might make it easy to miss. As someone who has other integrations with multi-page configurations, it's hard to remember what's on each page and where it is.

**Comment by agittins** [comment] 2024-06-29 13:28
Duplicate of #45

**Comment by agittins** [comment] 2024-06-29 13:30
I'm going to close this one out and track progress on the original issue #45 which will include both per-proxy offset for `ref_power` and a toggle to select whether to use the given proxy for calculations or not.

**Closed by agittins** 2024-06-29 13:30 UTC
