### ISSUE TITLE
Is there any way to tone down an overpowering BT Proxy to restore functionality of Bermuda?

### ISSUE THREAD

**Issue by chadbaum** [agittins/bermuda#293] opened 2024-08-20 19:26 UTC
I understand that per-device settings are on the roadmap but I have an issue where I have 1 BT Proxy that completely overpowers all the others, at any area global setting to the point where I can have another BT Proxy right next to me and my Apple Watch (which itself is a great client and very responsive) always report me as in the room of that 1 BT Proxy.  Is there anything I can do in the esphome config for that one to balance it out in anticipation of these per-device settings?

If it helps, I have 4 BT Proxy's on an Atom device.  The overpowering BT Proxy in question is an Everything Presence One.

Thanks!

**Comment by agittins** [comment] 2024-08-21 15:38
Howdy! 

That's good news for ep1 owners at least, that the antenna works so well! 😄

I'm not aware of any option in esphome that could control this, but it's a clever place to look for a solution. 

The really good news is that there's a beta version, 0.6.9rc2 that has this feature in it now, and it will be in the next official release. This is from @Lash-L 's commit #275 

You can try out v0.6.9 right now in HACS by choosing "re-download" and enabling "show beta versions".

I'm going to close this issue as a duplicate of #45 but please feel free to follow that issue for updates or if you have questions. 👍🏼

**Comment by agittins** [comment] 2024-08-21 15:39
Duplicate of #45

**Closed by agittins** 2024-08-21 15:38 UTC

**Comment by chadbaum** [comment] 2024-08-21 15:41
@agittins :  Lovely, thank you.  Will check it out.

**Comment by chadbaum** [comment] 2024-08-21 15:56
Looks like the UI and functionality for it is not fully-baked yet so I'll just wait until it's stable.  Good to know it's incoming.  I'll just shut down the EP1's for now.  Who knew their antennas were so good.

**Comment by agittins** [comment] 2024-08-22 03:23
Hmm... did you have any particular trouble with it?

The functionality should be OK, but the UI is admittedly... a bit ugly. The reason for that is that the config flow in HA isn't built for dynamically-created forms, so we are sort of abusing the UI features a bit.

I was having a lot of trouble coming up with a clean way to implement the user interface but that also provided enough info to be able to guide people through it without needing separate instructions.

I'd value your feedback on which parts of it in particular are off-putting. Some points that I think are a big "kludgy" are:
- The table of values might not render well on some devices, and also takes up a lot of vertical space per-row.
- The idea of hitting "Submit" to refresh the data, and having to tick a "Save and close" box is really un-homeassistanty, and also not very intuitive (hence the wordy instructions). Ideas are welcome here.
- Knowing how to pick good values is hard, so maybe the entire thing just looks overwhelming.

Does any of that ring true, or is there something else you ran into?

**Comment by chadbaum** [comment] 2024-08-22 14:54
Hey--happy to help here!  I actually wasn't even knitpicking about the UI/UX (but I will admit I work in the industry :P), for me when I tried to use it, the dialog boxes that popped up seemed unfinished and when I tried to input values, it didn't seem to work.  So it was purely a functional thing.  For example, there were some checkboxes that had no labels and I didn't know what they did.  Given that, I figured it was very early and maybe not ready for people like me to review.

Happy to try again.  I had re-flashed the EP1 without BT Proxy to disable it for now, but I can go re-flash it and take some screenshots and ask more questions.  I just figured it wasn't a good use of your time to hold my hand until it's in RC or release.

**Comment by agittins** [comment] 2024-08-23 06:52
> Hey--happy to help here!

Awesome! I appreciate the input.

> the dialog boxes that popped up seemed unfinished and when I tried to input values, it didn't seem to work. So it was purely a functional thing. For example, there were some checkboxes that had no labels and I didn't know what they did. Given that, I figured it was very early and maybe not ready for people like me to review.

Fair conclusion! 😅 rc2 should be functional, so maybe I've got some i18n work to do, perhaps.

Ahh... did you perhaps take the commit from the initial merge? We've made quite a few changes since that, so rc2 has a much different appearance and functionality than the initial commit. I probably should have linked the rc2 tag rather than the initial commit, sorry - I was keen to acknowledge Luke's work. https://github.com/agittins/bermuda/releases/tag/v0.6.9rc2

> Happy to try again. I had re-flashed the EP1 without BT Proxy to disable it for now, but I can go re-flash it and take some screenshots and ask more questions. I just figured it wasn't a good use of your time to hold my hand until it's in RC or release.

If what you had tried was an untagged commit then I think you'd have a much better time trying v0.6.9rc2, but if you were running rc2 I'd be especially interested in some screenshots and notes, because it's been working on my systems OK (but being a bit close to it makes it easy to miss details, plus HA's front-end caching means I might not notice something broken in the UI strings).

**Comment by chadbaum** [comment] 2024-09-03 14:20
Hi @agittins , sorry for the delay -- I was away on vacation the last week.  I'm happy to redownload rc2 and try again and then let you know where/if I am facing some blockers.  Will report back in 1-2 days.

Cheers
